language: cpp

sudo: false

compiler: clang

addons:
  apt:
    update: true
    sources:  [ 'george-edison55-precise-backports' ]
    packages: [ 'cmake', 'cmake-data' ]

matrix:
  exclude:
    - os: linux
  include:
    - os: osx
      osx_image: xcode9.3
      env: MASON_PLATFORM=ios
    - os: osx
      osx_image: xcode9.3
      env: MASON_PLATFORM=osx
    - os: linux
      dist: trusty
      env: MASON_PLATFORM=linux
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
