language: cpp
sudo: false

os:
  - linux

addons:
  apt_packages:
    - xutils-dev
env:
  global:
   - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
   - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="
  matrix:
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
   - MASON_PLATFORM=android MASON_ANDROID_ABI=x86
   - MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
   - MASON_PLATFORM=android MASON_ANDROID_ABI=mips
   - MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64
   - MASON_PLATFORM=linux

before_install:

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
