#!/bin/bash

MASON_COMMAND=$1
MASON_NAME=$2
MASON_VERSION=$3

function usage {
    echo "Usage: $0 <command> <lib> <version>"
}

if [ -z "${MASON_COMMAND}" ]; then
    usage
    exit 1
fi

if [ "${MASON_COMMAND}" = "selfupdate" ]; then
    cd ~/.mason
    git pull origin master
    exit
fi

if [ -z "${MASON_NAME}" ]; then
    usage
    echo "Missing <lib>"
    exit 1
elif [ -z "${MASON_VERSION}" ]; then
    usage
    echo "Missing <version>"
    exit 1
fi

. ~/.mason/mason.sh


# Load script if it doesn't exist yet
MASON_SCRIPT="${MASON_ROOT}/.scripts/${MASON_SLUG}.sh"

if [ ! -f "${MASON_SCRIPT}" ]; then
    mason_step "Loading install script 'https://github.com/mapbox/mason/blob/${MASON_SLUG}/script.sh'..."
    mkdir -p "${MASON_ROOT}/.scripts"
    curl -f -# -L https://raw.githubusercontent.com/mapbox/mason/${MASON_SLUG}/script.sh -o "${MASON_ROOT}/.scripts/${MASON_SLUG}.sh"
fi

bash "${MASON_SCRIPT}" "${MASON_COMMAND}"
