#!/bin/bash

MASON_COMMAND=$1
MASON_NAME=$2
MASON_VERSION=$3

function usage {
    echo "Usage: $0 <command> <lib> <version>"
    echo "Commands: install, remove, prefix"
}

if [ -z "${MASON_COMMAND}" ]; then
    usage
    exit 1
fi

if [ "${MASON_COMMAND}" = "selfupdate" ]; then
    cd /usr/local/share/mason
    git pull
    exit
fi

if [ -z "${MASON_NAME}" ]; then
    usage
    echo "Missing <lib>"
    exit 1
elif [ -z "${MASON_VERSION}" ]; then
    usage
    echo "Missing <version>"
    exit 1
fi

. /usr/local/share/mason/mason.sh


if [ "${MASON_COMMAND}" = "install" ]; then
    mason_step "Loading install script 'https://github.com/mapbox/mason/blob/${MASON_SLUG}/script.sh'..."
    curl -f -# -L https://raw.githubusercontent.com/mapbox/mason/${MASON_SLUG}/script.sh | bash
elif [ "${MASON_COMMAND}" = "remove" ]; then
    mason_step "Removing installation..."
    rm -rfv ${MASON_PREFIX}
elif [ "${MASON_COMMAND}" = "prefix" ]; then
    if [ ! -d "${MASON_PREFIX}" ]; then
        mason_error "Version '${MASON_VERSION}' of package '${MASON_NAME}' does not exist"
        exit 1
    fi

    echo ${MASON_PREFIX}
else
    usage
    mason_error "Unknown command '${MASON_COMMAND}'"
    exit 1
fi
