language: generic
compiler: gcc
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-5-dev
           - g++-5
           - bison
           - texinfo

# override install to prefer g++ instead of clang++
install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install gcc@5
      brew link --overwrite gcc@5
      export MASON_IGNORE_OSX_SDK=true
    fi
  - export CXX=g++-5
  - export CC=gcc-5

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
