sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: osx
      env: MASON_PLATFORM=ios
      osx_image: xcode8.2
      compiler: clang
    - os: linux
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++-4.9-dev
     - libstdc++6

script:
- |
  if [[ ${MASON_PLATFORM} == 'ios' ]] || [[ ${MASON_PLATFORM} == 'android' ]]; then
    MASON_PLATFORM= MASON_ANDROID_ABI= ./mason install ${MASON_NAME} ${MASON_VERSION}
    export PATH=`MASON_PLATFORM= MASON_ANDROID_ABI= ./mason prefix ${MASON_NAME} ${MASON_VERSION}`/bin:$PATH
  fi
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
