language: cpp
sudo: false

os:
  - linux

addons:
  apt_packages:
    - xutils-dev
matrix:
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
   - MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
   - MASON_PLATFORM=android MASON_ANDROID_ABI=x86
   - MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
   - MASON_PLATFORM=android MASON_ANDROID_ABI=mips
   - MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64
   - MASON_PLATFORM=linux

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
