language: cpp
    
matrix:
    include:
      - os: osx
        compiler: clang
        sudo: false
      - os: osx
        env: MASON_PLATFORM=ios
        compiler: clang
      - os: linux
        env: MASON_PLATFORM_VERSION=cortex_a9
      - os: linux
        env: MASON_PLATFORM_VERSION=i686
      - os: linux
        compiler: clang
        sudo: false
        addons:
          apt:
            sources:
             - ubuntu-toolchain-r-test
            packages:
             - libstdc++-5-dev
             - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
        addons:
          apt:
            packages:
              - xutils-dev
      - os: linux
        env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64
        addons:
          apt:
            packages:
              - xutils-dev

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
