language: generic

matrix:
  include:
    - os: osx
      compiler: clang
      sudo: false
    - os: osx
      env: MASON_PLATFORM=ios
      compiler: clang
    - os: linux
      compiler: clang
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-5-dev
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    - os: osx
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64

env:
  global:
   - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
   - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
