language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: linux
      sudo: false
      compiler: clang
      env: MASON_PLATFORM_VERSION=cortex_a9
    - os: linux
      sudo: false
      compiler: clang
      env: MASON_PLATFORM_VERSION=i686
    - os: linux
      sudo: false
      compiler: clang
      env: MASON_PLATFORM_VERSION=x86_64
    - os: linux
      sudo: false
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: linux
      sudo: false
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: linux
      sudo: false
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: linux
      sudo: false
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
