language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7
      compiler: clang
    - os: linux
      env: MASON_PLATFORM_VERSION=i686
    - os: linux
      env: MASON_PLATFORM_VERSION=cortex_a9
    - os: linux
      compiler: clang
      sudo: false
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
