language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7
      env: MASON_PLATFORM=ios
    - os: osx
      osx_image: xcode7
      env: MASON_PLATFORM=osx
    - os: linux
      compiler: gcc
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6
           - g++-5
      env: MASON_PLATFORM=linux

env:
  global:
   - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
   - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="

script:
- |
  if [[ ${MASON_PLATFORM} == 'linux' ]]; then
    export CXX=g++-5
    export CC=gcc-5
  fi
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}

