language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    #- os: linux
    #  env: MASON_PLATFORM_VERSION=i686
    #  sudo: false
    #  addons:
    #    apt:
    #      packages: [ 'zlib1g-dev:i386' ]
    - os: linux
      env: MASON_PLATFORM=linux
      compiler: clang
      sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    #  sudo: false
    #- os: linux
    #  env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64
    #  sudo: false

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
